// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc.proto

package server_side_stream

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CalReq struct {
	Valx                 *int32   `protobuf:"varint,1,req,name=valx" json:"valx,omitempty"`
	Valy                 *int32   `protobuf:"varint,2,req,name=valy" json:"valy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalReq) Reset()         { *m = CalReq{} }
func (m *CalReq) String() string { return proto.CompactTextString(m) }
func (*CalReq) ProtoMessage()    {}
func (*CalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_0e84c1d67991cf4d, []int{0}
}
func (m *CalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalReq.Unmarshal(m, b)
}
func (m *CalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalReq.Marshal(b, m, deterministic)
}
func (dst *CalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalReq.Merge(dst, src)
}
func (m *CalReq) XXX_Size() int {
	return xxx_messageInfo_CalReq.Size(m)
}
func (m *CalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CalReq.DiscardUnknown(m)
}

var xxx_messageInfo_CalReq proto.InternalMessageInfo

func (m *CalReq) GetValx() int32 {
	if m != nil && m.Valx != nil {
		return *m.Valx
	}
	return 0
}

func (m *CalReq) GetValy() int32 {
	if m != nil && m.Valy != nil {
		return *m.Valy
	}
	return 0
}

type CalRes struct {
	Result               *int32   `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalRes) Reset()         { *m = CalRes{} }
func (m *CalRes) String() string { return proto.CompactTextString(m) }
func (*CalRes) ProtoMessage()    {}
func (*CalRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_calc_0e84c1d67991cf4d, []int{1}
}
func (m *CalRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalRes.Unmarshal(m, b)
}
func (m *CalRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalRes.Marshal(b, m, deterministic)
}
func (dst *CalRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalRes.Merge(dst, src)
}
func (m *CalRes) XXX_Size() int {
	return xxx_messageInfo_CalRes.Size(m)
}
func (m *CalRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CalRes.DiscardUnknown(m)
}

var xxx_messageInfo_CalRes proto.InternalMessageInfo

func (m *CalRes) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*CalReq)(nil), "server.side.stream.CalReq")
	proto.RegisterType((*CalRes)(nil), "server.side.stream.CalRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalcClient is the client API for Calc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalcClient interface {
	Calcs(ctx context.Context, in *CalReq, opts ...grpc.CallOption) (Calc_CalcsClient, error)
}

type calcClient struct {
	cc *grpc.ClientConn
}

func NewCalcClient(cc *grpc.ClientConn) CalcClient {
	return &calcClient{cc}
}

func (c *calcClient) Calcs(ctx context.Context, in *CalReq, opts ...grpc.CallOption) (Calc_CalcsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calc_serviceDesc.Streams[0], "/server.side.stream.Calc/Calcs", opts...)
	if err != nil {
		return nil, err
	}
	x := &calcCalcsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calc_CalcsClient interface {
	Recv() (*CalRes, error)
	grpc.ClientStream
}

type calcCalcsClient struct {
	grpc.ClientStream
}

func (x *calcCalcsClient) Recv() (*CalRes, error) {
	m := new(CalRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalcServer is the server API for Calc service.
type CalcServer interface {
	Calcs(*CalReq, Calc_CalcsServer) error
}

func RegisterCalcServer(s *grpc.Server, srv CalcServer) {
	s.RegisterService(&_Calc_serviceDesc, srv)
}

func _Calc_Calcs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CalReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalcServer).Calcs(m, &calcCalcsServer{stream})
}

type Calc_CalcsServer interface {
	Send(*CalRes) error
	grpc.ServerStream
}

type calcCalcsServer struct {
	grpc.ServerStream
}

func (x *calcCalcsServer) Send(m *CalRes) error {
	return x.ServerStream.SendMsg(m)
}

var _Calc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.side.stream.Calc",
	HandlerType: (*CalcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Calcs",
			Handler:       _Calc_Calcs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calc.proto",
}

func init() { proto.RegisterFile("calc.proto", fileDescriptor_calc_0e84c1d67991cf4d) }

var fileDescriptor_calc_0e84c1d67991cf4d = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4e, 0xcc, 0x49,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2a, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b,
	0xce, 0x4c, 0x49, 0xd5, 0x2b, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0x55, 0x32, 0xe0, 0x62, 0x73, 0x4e,
	0xcc, 0x09, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0x29, 0x4b, 0xcc, 0xa9, 0x90, 0x60, 0x54, 0x60,
	0xd2, 0x60, 0x0d, 0x02, 0xb3, 0xa1, 0x62, 0x95, 0x12, 0x4c, 0x70, 0xb1, 0x4a, 0x25, 0x05, 0xa8,
	0x8e, 0x62, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xa8, 0x1e, 0x28, 0xcf,
	0xc8, 0x9b, 0x8b, 0xc5, 0x39, 0x31, 0x27, 0x59, 0xc8, 0x99, 0x8b, 0x15, 0x44, 0x17, 0x0b, 0x49,
	0xe9, 0x61, 0xda, 0xac, 0x07, 0xb1, 0x56, 0x0a, 0xb7, 0x5c, 0xb1, 0x12, 0x83, 0x01, 0x23, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x26, 0xbc, 0x8b, 0xe1, 0xc1, 0x00, 0x00, 0x00,
}
